### ISSUE TITLE
Should we apply head and tail from page content?

### ISSUE THREAD

**Issue by benoit74** [openzim/mindtouch#10]
In addition to MathJax #9, we have other "things" in `head` and `tail` attributes of page content.

Do we need / want to include these?

**Comment by rgaudin** [comment]
Haven't looked in detail but I think that if those are _attributes_ to some node and that you ask the question then there is no clear usage and thus it should not be included.
I understand this scraper is a _standard_ scraper: ie. we build up our ZIM with data we scraped ; in opposition to zimit where we pass data from website to ZIM with some transformation

**Comment by benoit74** [comment]
Intention so far is indeed to better understand what is in these attributes and if there is a usage / `use-case.`

**Comment by benoit74** [comment]
We are close to having completed v0.1 and it is now clear that we do not them so far. I've analyzed their content and they do not look relevant. Let's close this issue for now, and reopen if needed.
