### ISSUE TITLE
Rename the scraper / repo

### ISSUE THREAD

**Issue by benoit74** [openzim/mindtouch#6]
While this repo was originally targeted at making ZIMs for libretext, it is now clear that:
- libretexts is in fact based on [Mindtouch](https://en.wikipedia.org/wiki/MindTouch) (formerly DekiWiki, a fork of MediaWiki, now rebranded Nice CXOne Expert)
- the scraper seems to move in a direction where it would probably easily support any Mindtouch instance (small adapations might be necessary, but the move seems ongoing)

This is not something to answer now, but probably before first release.

**Comment by kelson42** [comment]
Agree, the sooner the better (think about code types and variable names).

**Comment by benoit74** [comment]
While developing, it is becoming quite obvious that there is probably some particularities around libretexts implementation, or at least areas where it is doubtful it will be "like this" on all mindtouch instances.

Since we do not have another mindtouch instance for testing, and do not have the adequate resources

I however recommend to still rename the scraper asap, keeping a warning on front page that this scraper has for now been tested only on one mindtouch instance and might probably have some rough edges to fix when moving to another one.

The reason is that:
- these rough edges seems feasible to overcome
- keeping `libretexts` name would not allow to "advertise" clearly we might have almost working support of any mindtouch instance
- probably 80% of the code needing to scraper any mindtouch instance will be already done
- should we move to `mindtouch` later-on, it means that we have too much to clean-up: code + docker repo + pypi + zimfarm + ...

@kelson42 @rgaudin are you ok with this move? Shall we use `mindtouch` as name, which is both nicer and easier to spell than `nicecxoneexpert`?

**Comment by rgaudin** [comment]
LGTM ; I have no opinion on the name to use though
