### ISSUE TITLE
Do not raise generic `Exception`, prefer qualified exception

### ISSUE THREAD

**Issue by benoit74** [openzim/mindtouch#91]
We should avoid to raise generic `Exception` and prefer qualified exception, either choosing one from the stdlib or creating our own.

**Comment by Gulin7** [comment]
Hi, @benoit74 , could I take this issue?

**Comment by benoit74** [comment]
Definitely, you're welcomed! I've assigned you the issue, please send a PR (from your fork of this repository) once ready (and read details of https://github.com/openzim/overview/wiki/openZIM-code-contribution-workflow)

Nota: I don't know I've you've seen rgaudin suggestions of using `OSError` in a bunch of cases, but I'm not totally convinced by the choice of this exception, feel free to propose something of your own ^^

**Comment by Gulin7** [comment]
I also suggest moving all Custom exceptions to the errors.py file, for example this one: https://github.com/openzim/mindtouch/blob/92fafb16c6d7d92615964a942b60aaf12f0876fc/scraper/src/mindtouch2zim/client.py#L19

**Comment by Gulin7** [comment]
I have created a Pull Request: #103
